### PR TITLE
many mostly win32-ish fixes

### PR DESCRIPTION
**Pull request by bulk88**
Most of these are about machine code size, or Win32 I/O overhead. Since directory cache got enabled for Win32, there is alot less kernel time (red line in task man) involved when doing -P3 building, and the lag before parallel perl compiling starts is shorter since the directory cache is faster than going to the NTFS driver/kernel each time now dmake is CPU bound in user mode. See the 2 pics I attached of post optimized (head of this pull request) show the problem is now user mode bound in CPU, specifically the inefficent way that it looks for things to build (the DAG is expanded into a perfect tree and every node on it checked) and inefficiently assembling file path names to query the dir cache. Ive no comnpiling with autoconf on win32, unix builds, or anything but VC. I also haven't run any of the included tests, but compiling parallel perl seems to work fine.

Some timings according to windows kernel showing improvements over time. The cmd BELOW the times is what was used to run the above. The makefile.mk I used for perl is not the P5P one but it is the same for all the tests. System calls # is practically random between run to run and differs by +/- 5 million each run. elapsed time is also useless since that would be benchmarking Perl and EUMM and VC compiler. So only process time, with its 15 to 50 ms resolution is useful.

after dchdir remove \/
Version Number:   Windows NT 5.1 (Build 2600)
Exit Time:        2:31 am, Saturday, February 21 2015
Elapsed Time:     0:03:53.312
Process Time:     0:00:00.484
System Calls:     15553953
Context Switches: 276514
Page Faults:      5753212
Bytes Read:       1356537036
Bytes Written:    169750580
Bytes Other:      371318451

C:\perl521\srcnewb4opt\win32>b88dmake -P3 all

before dchdir remove \/
my dmake
Version Number:   Windows NT 5.1 (Build 2600)
Exit Time:        11:08 pm, Friday, February 20 2015
Elapsed Time:     0:03:51.015
Process Time:     0:00:00.578
System Calls:     16219382
Context Switches: 2486903
Page Faults:      5531610
Bytes Read:       1301749972
Bytes Written:    144773367
Bytes Other:      272659760

C:\perl521\srcnewb4opt\win32>timeit b88dmake -P3 all

Version Number:   Windows NT 5.1 (Build 2600)
Exit Time:        11:22 pm, Friday, February 20 2015
Elapsed Time:     0:03:54.750
Process Time:     0:00:01.765
System Calls:     16489168
Context Switches: 2454619
Page Faults:      5550602
Bytes Read:       1307716071
Bytes Written:    141168260
Bytes Other:      304032904

C:\perl521\srcnewb4opt\win32>timeit b88dmake -d -P3 all

strawberry 5.18's dmake

Version Number:   Windows NT 5.1 (Build 2600)
Exit Time:        11:12 pm, Friday, February 20 2015
Elapsed Time:     0:03:42.671
Process Time:     0:00:01.843
System Calls:     14987765
Context Switches: 2246058
Page Faults:      5503661
Bytes Read:       1281856060
Bytes Written:    138079099
Bytes Other:      254401591

C:\perl521\srcnewb4opt\win32>timeit dmake -P3 all

fncs sorted by alone time
fncs sorted by with children time

### CODE REVIEW

**Comment by bulk88** [comment]
added some more commits,  strpbrk b4 and after pics, large decrease in calls to strchr
use strpbrk b4
use strpbrk after

cachestat dont dup str commit before and after, cachestat's average with children time went from 22 us to 14 us and 26% of all execution time to 19%
cache stat dont dup str path compute b4
cache stat dont dup str path compute after

**Comment by bulk88** [comment]
Rebased on new mohawk master. This is without commit "Special-case brk == NULL and short-cut." which was causing major breakage for me.

**Comment by bulk88** [comment]
commit "replace special DOS dmake version of chdir, with CRT chdir on Win32" 's original message was much longer and was therefore shortened, is here pasted here for history reasons
```
remove _chdrive usage for Win32

_chdrive is implemented with _chdir/SetCurrentDirectory.
It is pointless to call _chdrive after _chdir since _chdir will set
the current drive automatically. Each SetCurrentDirectory, if it detects
the new path is different from the previous path is has internally, does
3 kernel IO calls. dmake's dchdir guarentees that the processes CWD will
needlessly change every time between C:\ and C:\to\the\src\code, and the
IO calls SetCurrentDirectory has to make to verify the new path exists.
As a side note Win32 Perl doesn't use _chdrive, just SetCurrentDirectory.
To reduce the amount of IO calls and CPU, just use the CRT's normal
_chdir function.

Below are the stack traces of the 6 kernel calls that
dchdir was making

ntdll.dll!_KiFastSystemCall@0()
ntdll.dll!_ZwOpenFile@24()  + 0xc
ntdll.dll!_RtlSetCurrentDirectory_U@4()  + 0x133
kernel32.dll!_SetCurrentDirectoryA@4()  + 0x2a
dmake.exe!_chdir(const char * path=0x00332d50)  Line 49 + 0x7	C
dmake.exe!dchdir(char * path=0x00332d50)  Line 38 + 0x9	C
dmake.exe!Set_dir(char * path=0x00332d50)  Line 625 + 0x9	C
dmake.exe!CacheStat()  Line 183 + 0xb	C
dmake.exe!Do_stat(char * name=0x009e15b0, char * lib=0x00000000, char * * member=0x00000000, int force=0x00000000)  Line 125 + 0xd	C
dmake.exe!_check_dir_list(tcell * cp=0x009e1620, tcell * sp=0x0033b990, int setfname=0x00000001, int force=0x00000000)  Line 250 + 0x11	C
dmake.exe!Stat_target(tcell * cp=0x009e1620, int setfname=0x00000001, int force=0x00000000)  Line 141 + 0x1b	C
dmake.exe!Make(tcell * cp=0x009e1620, tcell * setdirroot=0x00000000)  Line 391 + 0xd	C
dmake.exe!Make(tcell * cp=0x00a008f0, tcell * setdirroot=0x00000000)  Line 587 + 0xd	C
dmake.exe!Make(tcell * cp=0x0033b2b0, tcell * setdirroot=0x00000000)  Line 587 + 0xd	C
dmake.exe!Make(tcell * cp=0x00334098, tcell * setdirroot=0x00000000)  Line 587 + 0xd	C
dmake.exe!Make(tcell * cp=0x003310d8, tcell * setdirroot=0x00000000)  Line 587 + 0xd	C
dmake.exe!Make(tcell * cp=0x00331028, tcell * setdirroot=0x00000000)  Line 587 + 0xd	C
dmake.exe!Make_targets()  Line 242 + 0xe	C
dmake.exe!main(int argc=0x00000000, char * * argv=0x003312b0)  Line 478 + 0x5	C
dmake.exe!mainCRTStartup()  Line 259 + 0x12	C
kernel32.dll!_BaseProcessStart@4()  + 0x23

ntdll.dll!_KiFastSystemCall@0()
ntdll.dll!_NtQueryVolumeInformationFile@20()  + 0xc
ntdll.dll!_RtlSetCurrentDirectory_U@4()  + 0x152
kernel32.dll!_SetCurrentDirectoryA@4()  + 0x2a
dmake.exe!_chdir(const char * path=0x00332d50)  Line 49 + 0x7	C
dmake.exe!dchdir(char * path=0x00332d50)  Line 38 + 0x9	C
dmake.exe!Set_dir(char * path=0x00332d50)  Line 625 + 0x9	C
dmake.exe!CacheStat()  Line 183 + 0xb	C
dmake.exe!Do_stat(char * name=0x009e15b0, char * lib=0x00000000, char * * member=0x00000000, int force=0x00000000)  Line 125 + 0xd	C
dmake.exe!_check_dir_list(tcell * cp=0x009e1620, tcell * sp=0x0033b990, int setfname=0x00000001, int force=0x00000000)  Line 250 + 0x11	C
dmake.exe!Stat_target(tcell * cp=0x009e1620, int setfname=0x00000001, int force=0x00000000)  Line 141 + 0x1b	C
dmake.exe!Make(tcell * cp=0x009e1620, tcell * setdirroot=0x00000000)  Line 391 + 0xd	C
dmake.exe!Make(tcell * cp=0x00a008f0, tcell * setdirroot=0x00000000)  Line 587 + 0xd	C
dmake.exe!Make(tcell * cp=0x0033b2b0, tcell * setdirroot=0x00000000)  Line 587 + 0xd	C
dmake.exe!Make(tcell * cp=0x00334098, tcell * setdirroot=0x00000000)  Line 587 + 0xd	C
dmake.exe!Make(tcell * cp=0x003310d8, tcell * setdirroot=0x00000000)  Line 587 + 0xd	C
dmake.exe!Make(tcell * cp=0x00331028, tcell * setdirroot=0x00000000)  Line 587 + 0xd	C
dmake.exe!Make_targets()  Line 242 + 0xe	C
dmake.exe!main(int argc=0x00000000, char * * argv=0x003312b0)  Line 478 + 0x5	C
dmake.exe!mainCRTStartup()  Line 259 + 0x12	C
kernel32.dll!_BaseProcessStart@4()  + 0x23

ntdll.dll!_KiFastSystemCall@0()
ntdll.dll!_NtClose@4()  + 0xc
ntdll.dll!_RtlSetCurrentDirectory_U@4()  - 0xb015
kernel32.dll!_SetCurrentDirectoryA@4()  + 0x2a
dmake.exe!_chdir(const char * path=0x00332d50)  Line 49 + 0x7	C
dmake.exe!dchdir(char * path=0x00332d50)  Line 38 + 0x9	C
dmake.exe!Set_dir(char * path=0x00332d50)  Line 625 + 0x9	C
dmake.exe!CacheStat()  Line 183 + 0xb	C
dmake.exe!Do_stat(char * name=0x009e15b0, char * lib=0x00000000, char * * member=0x00000000, int force=0x00000000)  Line 125 + 0xd	C
dmake.exe!_check_dir_list(tcell * cp=0x009e1620, tcell * sp=0x0033b990, int setfname=0x00000001, int force=0x00000000)  Line 250 + 0x11	C
dmake.exe!Stat_target(tcell * cp=0x009e1620, int setfname=0x00000001, int force=0x00000000)  Line 141 + 0x1b	C
dmake.exe!Make(tcell * cp=0x009e1620, tcell * setdirroot=0x00000000)  Line 391 + 0xd	C
dmake.exe!Make(tcell * cp=0x00a008f0, tcell * setdirroot=0x00000000)  Line 587 + 0xd	C
dmake.exe!Make(tcell * cp=0x0033b2b0, tcell * setdirroot=0x00000000)  Line 587 + 0xd	C
dmake.exe!Make(tcell * cp=0x00334098, tcell * setdirroot=0x00000000)  Line 587 + 0xd	C
dmake.exe!Make(tcell * cp=0x003310d8, tcell * setdirroot=0x00000000)  Line 587 + 0xd	C
dmake.exe!Make(tcell * cp=0x00331028, tcell * setdirroot=0x00000000)  Line 587 + 0xd	C
dmake.exe!Make_targets()  Line 242 + 0xe	C
dmake.exe!main(int argc=0x00000000, char * * argv=0x003312b0)  Line 478 + 0x5	C
dmake.exe!mainCRTStartup()  Line 259 + 0x12	C
kernel32.dll!_BaseProcessStart@4()  + 0x23

ntdll.dll!_KiFastSystemCall@0()
ntdll.dll!_ZwOpenFile@24()  + 0xc
ntdll.dll!_RtlSetCurrentDirectory_U@4()  + 0x133
kernel32.dll!_SetCurrentDirectoryA@4()  + 0x2a
dmake.exe!_chdrive(int drive=0x00003a43)  Line 119 + 0x12	C
dmake.exe!dchdir(char * path=0x00a086b8)  Line 45 + 0x9	C
dmake.exe!Set_dir(char * path=0x00a086b8)  Line 625 + 0x9	C
dmake.exe!CacheStat()  Line 158 + 0x9	C
dmake.exe!Do_stat(char * name=0x0033dc40, char * lib=0x00000000, char * * member=0x00000000, int force=0x00000000)  Line 125 + 0xd	C
dmake.exe!_check_dir_list(tcell * cp=0x00334098, tcell * sp=0x0033b990, int setfname=0x00000001, int force=0x00000000)  Line 250 + 0x11	C
dmake.exe!Stat_target(tcell * cp=0x00334098, int setfname=0x00000001, int force=0x00000000)  Line 141 + 0x1b	C
dmake.exe!Make(tcell * cp=0x00334098, tcell * setdirroot=0x00000000)  Line 391 + 0xd	C
dmake.exe!Make(tcell * cp=0x003310d8, tcell * setdirroot=0x00000000)  Line 587 + 0xd	C
dmake.exe!Make(tcell * cp=0x00331028, tcell * setdirroot=0x00000000)  Line 587 + 0xd	C
dmake.exe!Make_targets()  Line 242 + 0xe	C
dmake.exe!main(int argc=0x00000000, char * * argv=0x003312b0)  Line 478 + 0x5	C
dmake.exe!mainCRTStartup()  Line 259 + 0x12	C
kernel32.dll!_BaseProcessStart@4()  + 0x23

ntdll.dll!_KiFastSystemCall@0()
ntdll.dll!_NtQueryVolumeInformationFile@20()  + 0xc
ntdll.dll!_RtlSetCurrentDirectory_U@4()  + 0x152
kernel32.dll!_SetCurrentDirectoryA@4()  + 0x2a
dmake.exe!_chdrive(int drive=0x00003a43)  Line 119 + 0x12	C
dmake.exe!dchdir(char * path=0x00a086b8)  Line 45 + 0x9	C
dmake.exe!Set_dir(char * path=0x00a086b8)  Line 625 + 0x9	C
dmake.exe!CacheStat()  Line 158 + 0x9	C
dmake.exe!Do_stat(char * name=0x0033dc40, char * lib=0x00000000, char * * member=0x00000000, int force=0x00000000)  Line 125 + 0xd	C
dmake.exe!_check_dir_list(tcell * cp=0x00334098, tcell * sp=0x0033b990, int setfname=0x00000001, int force=0x00000000)  Line 250 + 0x11	C
dmake.exe!Stat_target(tcell * cp=0x00334098, int setfname=0x00000001, int force=0x00000000)  Line 141 + 0x1b	C
dmake.exe!Make(tcell * cp=0x00334098, tcell * setdirroot=0x00000000)  Line 391 + 0xd	C
dmake.exe!Make(tcell * cp=0x003310d8, tcell * setdirroot=0x00000000)  Line 587 + 0xd	C
dmake.exe!Make(tcell * cp=0x00331028, tcell * setdirroot=0x00000000)  Line 587 + 0xd	C
dmake.exe!Make_targets()  Line 242 + 0xe	C
dmake.exe!main(int argc=0x00000000, char * * argv=0x003312b0)  Line 478 + 0x5	C
dmake.exe!mainCRTStartup()  Line 259 + 0x12	C
kernel32.dll!_BaseProcessStart@4()  + 0x23

ntdll.dll!_KiFastSystemCall@0()
ntdll.dll!_NtClose@4()  + 0xc
ntdll.dll!_RtlSetCurrentDirectory_U@4()  - 0xb015
kernel32.dll!_SetCurrentDirectoryA@4()  + 0x2a
dmake.exe!_chdrive(int drive=0x00003a43)  Line 119 + 0x12	C
dmake.exe!dchdir(char * path=0x00a086b8)  Line 45 + 0x9	C
dmake.exe!Set_dir(char * path=0x00a086b8)  Line 625 + 0x9	C
dmake.exe!CacheStat()  Line 158 + 0x9	C
dmake.exe!Do_stat(char * name=0x0033dc40, char * lib=0x00000000, char * * member=0x00000000, int force=0x00000000)  Line 125 + 0xd	C
dmake.exe!_check_dir_list(tcell * cp=0x00334098, tcell * sp=0x0033b990, int setfname=0x00000001, int force=0x00000000)  Line 250 + 0x11	C
dmake.exe!Stat_target(tcell * cp=0x00334098, int setfname=0x00000001, int force=0x00000000)  Line 141 + 0x1b	C
dmake.exe!Make(tcell * cp=0x00334098, tcell * setdirroot=0x00000000)  Line 391 + 0xd	C
dmake.exe!Make(tcell * cp=0x003310d8, tcell * setdirroot=0x00000000)  Line 587 + 0xd	C
dmake.exe!Make(tcell * cp=0x00331028, tcell * setdirroot=0x00000000)  Line 587 + 0xd	C
dmake.exe!Make_targets()  Line 242 + 0xe	C
dmake.exe!main(int argc=0x00000000, char * * argv=0x003312b0)  Line 478 + 0x5	C
dmake.exe!mainCRTStartup()  Line 259 + 0x12	C
kernel32.dll!_BaseProcessStart@4()  + 0x23
```

**Comment by mohawk2** [comment]
This has now been merged (after further rebasing of master to move test changes into `quotefix` branch).

**Pull request closed without merging**
